version: '3.8'
services:
  development_database:
    image: mysql:9.4.0-oracle
    networks: 
      - meal_planner_app_network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
networks:
  meal_planner_app_network:
    driver: bridge
volumes:
  db_data:
    driver: local
