spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meal_planner_db?useSSL=false&allowPublicKeyRetrieval=true
    username: meal_planner_user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
